# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 234a525e4a4a9b0ada215a6d4de66b68b03b20f607c8963cd559b567838a9bb5523a8e8b81bfbe4d83f562d2ebeef7a8cffb80fb33fc68c85207d60a32b867bf

test:
  secret_key_base: 4a270ca11b49f4a48dc823db18d9a49716a31c37e748f473e4e0eee5ce5531f96f80a2cb19a91c9ab45d7c24021df679e622a344594bef8fff7c14105a4e0b89

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
